### PR TITLE
adapt reporter init options to changes in oboe ...

### PR DESCRIPTION
**Pull request by prettycoder**
the new options for lambda and grpc hack are hard-coded
- Ruby has not implemented lambda yet
- the grpc hack is always needed

### CODE REVIEW

**Comment by ronilan** [comment]
@prettycoder - what's happening here with the GH Actions tests? (manual trigger to C++ tests would be useful)

**Comment by prettycoder** [comment]
tests will pass after the profiling code PR

**Comment by prettycoder** [comment]
I'm gonna make a change to run the c++ tests only when the c-files change

**Comment by prettycoder** [comment]
I don't know why the manual trigger for c++ tests doesn't show, may after I merge the other PRs

**Comment by ronilan** [comment]
> I don't know why the manual trigger for c++ tests doesn't show, may after I merge the other PRs

The manual trigger option should show when merged to master for first time.

**Review by ronilan — APPROVED** [review]

**Pull request merged**
